#!/bin/bash

mkdir -p /mnt/config
umount -q /mnt/config || true
LODEV=$(losetup -f)
losetup -P "$LODEV" /dev/mmcblk2boot0
mount -r "$LODEV"p1 /mnt/config/ 2>/dev/null

cat /mnt/config/serial_number

umount /mnt/config
losetup -d "$LODEV"