#!/bin/bash

PATH_EMMC="/dev/"`lsblk -n -o NAME | grep 'mmcblk[0-2]$'`"p2"
PATH_USB="/dev/sda2"
UUID_EMMC=`lsblk -o UUID -n $PATH_EMMC 2>/dev/null`
UUID_USB=`lsblk -o UUID -n /dev/sda2 2>/dev/null`

DEV=`grep "^rootdev=" /boot/armbianEnv.txt | sed 's:rootdev=::' | sed 's:UUID=::'`

case $DEV in
  $PATH_EMMC | $UUID_EMMC)
    echo "emmc"
    ;;

  $PATH_USB | $UUID_USB)
  echo "usb"
  ;;

  *)
  echo "unknown"
  ;;

esac
