#!/bin/bash

MEDIA=$1
EMMC=`lsblk -n -o NAME | grep 'mmcblk[0-2]$'`

case $MEDIA in
  usb)
    if test -b "/dev/sda1"; then
      echo "yes"
    else
      echo "no"
    fi
    ;;

  emmc)
    if test -b "/dev/${EMMC}"; then
      echo "yes"
    else
      echo "no"
    fi
    ;;

  *)
  echo "usage $0 <emmc/usb>"
  ;;

esac
