#!/bin/bash

NEW_MEDIA=$1
EMMC=`lsblk -n -o NAME | grep 'mmcblk[0-2]$'`

PATH_EMMC="/dev/${EMMC}p2"
PATH_USB="/dev/sda2"
UUID_EMMC=`lsblk -o UUID -n $PATH_EMMC 2>/dev/null`
UUID_USB=`lsblk -o UUID -n /dev/sda2 2>/dev/null`

if [ "x${NEW_MEDIA}" == "xusb" ]; then
  NEW_DEV="/dev/sda2"
elif [ "x${NEW_MEDIA}" == "xemmc" ]; then
  NEW_DEV="UUID=$UUID_EMMC"
else
  echo "usage $0 usb/emmc"
  exit 1
fi

KEY="^rootdev=.*$"

mount -o remount -rw /boot
sed -i "s:${KEY}::g" /boot/armbianEnv.txt
sed -i '/^$/d' /boot/armbianEnv.txt
echo "rootdev=${NEW_DEV}" >> /boot/armbianEnv.txt
sync
mount -o remount -r /boot
