#!/bin/bash

set -e


REVISION=$(get-recore-revision)

FLASH_DEVICE=/dev/ttyS2

STM32_BINARY=/opt/firmware/stm32.bin
if [ "$REVISION" == "a7" ] ; then
    STM32_BINARY=/opt/firmware/stm32-32KB.bin
fi

systemctl stop klipper

gpioset 1 197=1
gpioset 1 196=0
gpioset 1 196=1
stm32flash -w ${STM32_BINARY} -v -g 0 ${FLASH_DEVICE}
gpioset 1 197=0
gpioget 1 196

systemctl disable flash-stm32
systemctl restart klipper
